metadata:
  name: ${project.artifactId}
data:
  config.json: |+
   {
     "listeners": [
       {
         "port": 8080,
         "filters": [
           {
             "type": "read",
             "name": "http_connection_manager",
             "config": {
               "codec_type": "auto",
               "stat_prefix": "ingress_http",
               "route_config": {
                 "virtual_hosts": [
                   {
                     "name": "backend",
                     "domains": ["*"],
                     "routes": [
                       {
                         "timeout_ms": 0,
                         "prefix": "${servicePath}",
                         "cluster": "my_service_cluster"
                       }
                     ]
                   }
                 ]
               },
               "filters": [
                 {
                   "type": "decoder",
                   "name": "router",
                   "config": {}
                 }
               ]
             }
           }
         ]
       }
     ],
     "admin": {
       "access_log_path": "/dev/null",
       "port": 8001
     },
     "cluster_manager": {
       "clusters": [
         {
           "name": "my_service_cluster",
           "connect_timeout_ms": 250,
           "type": "strict_dns",
           "lb_type": "round_robin",
           "features": "http2",
           "hosts": [
             {
               "url": "${serviceUrl}"
             }
           ],
           "circuit_breakers": {
              "default": {
                 "max_requests": 10
              }
           }
         }
       ]
     }
   }



