metadata:
  name: ${project.artifactId}
data:
  config.json: |+
   {
     "listeners": [
       {
         "port": 80,
         "filters": [
           {
             "type": "read",
             "name": "http_connection_manager",
             "config": {
               "codec_type": "auto",
               "stat_prefix": "ingress_http",
               "route_config": {
                 "virtual_hosts": [
                   {
                     "name": "backend",
                     "domains": ["*"],
                     "routes": [
                       {
                         "timeout_ms": 0,
                         "prefix": "/api/goodbye",
                         "cluster": "goodbye_springboot"
                       },
                      {
                        "timeout_ms": 0,
                        "prefix": "/api/nap",
                        "cluster": "goodbye_springboot"
                      }
                     ]
                   }
                 ]
               },
               "filters": [
                 {
                   "type": "decoder",
                   "name": "router",
                   "config": {}
                 }
               ]
             }
           }
         ]
       }
     ],
     "admin": {
       "access_log_path": "/dev/null",
       "port": 8001
     },
     "cluster_manager": {
       "clusters": [
         {
           "name": "goodbye_springboot",
           "connect_timeout_ms": 250,
           "type": "strict_dns",
           "lb_type": "round_robin",
           "features": "http2",
           "hosts": [
             {
               "url": "tcp://goodbye-server-springboo:80"
             }
           ]
         }
       ]
     }
   }



