---
apiVersion: v1
kind: Service
spec:
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    project: ${project.artifactId}
    provider: redhat-developers
    group: org.workspace7.msa
